[build]
  publish = "."

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"
